POST http://127.0.0.1:8000/api/auth/change-password
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3QiLCJleHAiOjE2MjM5Mjk5MDh9.lior3HtdLML3vAKU0-uNEB394Zw8VYu2oMvJqWxOwR4


{
    "old_password": "test",
    "new_password": "testnew"
}