GET http://127.0.0.1:8000/api/attendance/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwicGFzc3dvcmQiOiJhZG1pbiIsImV4cCI6MTYyNDUzMjQ0OH0.MYaXkJqL5QLw1H87uG7YOYykpy0A-5ZUmr6V8gdNCrQ

