POST http://127.0.0.1:8000/api/auth/update
content-type: application/json
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIn0.wNVf8EXDsI7ZqlX1Cx_a9yb829E4KQTGDeTwrv5zSxM

{
 "email": "admin@mail.com", 

  "total_hours": 20

   }