# Generated by Django 3.2.4 on 2021-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_has_module_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
