# Generated by Django 3.2.4 on 2021-06-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
